jobs:
  include:
    - language: node_js
      node_js:
        - 14
      before_install:
        - cd myapp
      install:
        - npm install react-bootstrap bootstrap
        - npm install axios
      script:
        - npm test

  include:
    - language: python
      install:
        - pip install flask
        - pip install flask-cors
        - pip install pymongo
        - pip install dnspython
      scipt:
        - pytest
