jobs:
  include:
    - language: node_js
      node_js: 14
      before_install:
        - cd myapp
      install:
        - npm install
      script:
        - npm test
        - npm run build

    - language: python
      python: 3.9
      before install:
        - cd myapp
      install:
        - pip install -r requirements.txt
      scipt:
        - pytest
