jobs:
  include:
    - language: node_js
      node_js: 14
      before_install:
        - cd myapp
      install:
        - npm install react-bootstrap bootstrap
        - npm install axios
      script:
        - npm test
        - npm run build

    - language: python
      python: 3.9
      install:i
        - pip install flask
        - pip install flask-cors
        - pip install pymongo
        - pip install dnspython
      scipt:
        - pytest
