from flask import Flask, request, jsonify 
from flask_cors import CORS 

app = Flask(__name__)
CORS(app)

proj_db = {
  'team_roster': [
    {
      'id': '1234',                     # Not displayed to roster page, will be generated by mongo
      'name': 'Darren Collins',                  
      'status' : 'active',              # Not displayed to roster page
      'role': 'Advisor',                # Not displayed to roster page
      'position' : 'Head Mentor',
      'photo': '', 
      'email': 'dc@gmail.com',         
      'phone_number': '805-555-1234',  
      'quote' : 'darren\'s quote'
    }, 
    {
      'id': '5678',                     # Not displayed to roster page, will be generated by mongo
      'name': 'Avery',                  
      'status' : 'active',              # Not displayed to roster page
      'role': 'Officer',                # Not displayed to roster page
      'position' : 'Programmer',
      'photo': '', 
      'email': 'avery@gmail.com',       
      'phone_number': '805-555-1111',  
      'quote' : 'avery\'s quote'
    }, 
    {
      'id': '1212',                     # Not displayed to roster page, will be generated by mongo
      'name': 'Jacob',                  
      'status' : 'active',              # Not displayed to roster page
      'role': 'Officer',                # Not displayed to roster page
      'position' : 'Lead Designer',
      'photo': '', 
      'email': 'jacobemail@gmail.com', 
      'phone_number': '805-555-1212',   
      'quote' : 'Something epic here'
    }, 
    {
      'id': '3434',                     # Not displayed to roster page, will be generated by mongo
      'name': 'Shane',                  
      'status' : 'active',              # Not displayed to roster page
      'role': 'Officer',                # Not displayed to roster page
      'position' : 'President',
      'photo': '', 
      'email': 'president@gmail.com',   
      'phone_number': '805-555-1234',  
      'quote' : 'Shane\'s quote'
    },
    {
      'id': '0001',                     # Not displayed to roster page, will be generated by mongo
      'name': 'MemberONE',                  
      'status' : 'active',              # Not displayed to roster page
      'role': 'Member',                 # Not displayed to roster page
      'position' : 'Member',
      'photo': '', 
      'email': 'memberone@gmail.com',   
      'phone_number': '805-555-0001',   
      'quote' : 'this is my quote here'
    }    
  ]
}


@app.route('/')
def hello_world():
    return 'Hello, World!'

@app.route('/teamroster', methods=['GET', 'POST'])
def get_team_roster():
  if request.method == 'GET':
    return proj_db
  
  elif request.method == 'POST':
    usertoAdd = request.get_json()
    proj_db['team_roster'].append(usertoAdd)
    resp = jsonify(usertoAdd)
    resp.status_code = 201
    return resp
