  
import React from 'react'

export const About = () => (
  <div>
    <h2>About Page</h2>
    <p>Blah blah blah.</p>
    <p>Stare at ceiling lay on arms while you're using the keyboard so this human feeds me, i should be a god wack the mini furry mouse but all of a sudden cat goes crazy get suspicious of own shadow then go play with toilette paper. All of a sudden cat goes crazy wake up human for food at 4am stick butt in face, and peer out window, chatter at birds, lure them to mouth, knock over christmas tree. Scamper run up and down stairs lie on your belly and purr when you are asleep but attack the child. Warm up laptop with butt lick butt fart rainbows until owner yells pee in litter box hiss at cats hiding behind the couch until lured out by a feathery toy leave hair everywhere have secret plans so meow meow, i tell my human, so bite the neighbor's bratty kid find empty spot in cupboard and sleep all day. Need to chase tail wake up human for food at 4am. Chase ball of string sniff catnip and act crazy throw down all the stuff in the kitchen hide from vacuum cleaner.</p>
    <p>Donec pharetra augue eu luctus consectetur. Quisque id porttitor velit, facilisis elementum tortor. Mauris sodales cursus ex, in maximus nisl aliquam non. Etiam eu risus urna. Nam ut consectetur ipsum. Maecenas mollis scelerisque libero. Praesent efficitur tortor id mi pharetra, in tempor arcu molestie. Quisque ut ultrices est, at efficitur dolor.</p>
    <p>Nulla volutpat eros non magna feugiat, quis gravida purus cursus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum id eros id ex tincidunt fermentum sit amet vitae erat. Morbi vulputate arcu facilisis lacus condimentum accumsan. In vehicula, velit sed scelerisque viverra, libero odio gravida ipsum, at maximus velit nisl sed enim. Vestibulum finibus ultricies sem nec euismod. Suspendisse suscipit accumsan purus in interdum. Nullam dolor arcu, pulvinar sed porta nec, rutrum sit amet felis. Donec id risus eu eros blandit finibus. Phasellus venenatis elit sed metus varius suscipit eget ut quam. Cras vestibulum fermentum egestas. Suspendisse pulvinar urna aliquet magna vulputate, vel consectetur dolor varius. Sed ut libero suscipit, pharetra ligula vitae, volutpat ligula. Donec dapibus leo non euismod tincidunt. Nulla efficitur porttitor leo, ac tristique felis sagittis vel.</p>
  </div>
)